name: comment-on-pr example
on: pull_request
jobs:
  example:
    name: how to review
    runs-on: ubuntu-latest
    steps:
      - name: Pull number
        run:   echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "HOW TO REVIEW:\n
- Test multiplayer (Client and Host)\n
- Check build status\n
- Check UI\n
- Check the code\n
- Check artifacts $PR_URI/checks\n
- <del>Is it working with translations?</del>\n
${PULL_NUMBER}"
          check_for_duplicate_msg: false  # Will change this after debugging 
